### ISSUE TITLE
PDF?

### ISSUE THREAD

**Issue by bradlindblad** [JuliaDocs/Julia-Cheat-Sheet#115]
Could we get this in PDF by chance?

**Comment by timothywalsh** [comment]
I second this question/suggestion. I would like a pdf version of this cheat sheet, so that I can print it out, like an old-fashioned cheat sheet.

Any advice on how to get this into a good looking pdf format would be welcome

**Comment by logankilpatrick** [comment]
[The Fast Track to Julia.pdf](https://github.com/JuliaDocs/Julia-Cheat-Sheet/files/6677108/The.Fast.Track.to.Julia.pdf)

This should be super easy with your browser! All you need to do is "File" -> Export as PDF. It looks really good and seems to work since this site only has one page.
