### ISSUE TITLE
update to Julia 1.6

### ISSUE THREAD

**Issue by waynelapierre** [JuliaDocs/Julia-Cheat-Sheet#134]
When will this cheatsheet be updated to Julia 1.6?

**Comment by hsugawa8651** [comment]
If we believe our content is up-to-date, why not change the page title to Julia Cheatsheet **1.6** or **1.x** ?

**Comment by cormullion** [comment]
I'd like to start updating this soon, but the first task will be to convert it to use Franklin.jl. since it currently uses Jekyll, and I hide from working with Jekyll blogs...
