### ISSUE TITLE
pkg.julialang.org is a Julia package server

### ISSUE THREAD

**Issue by Pranprest** [JuliaDocs/Julia-Cheat-Sheet#152]
The URL on line 1 from Package-management.md ("Packages must be [registered](https://pkg.julialang.org/) before they are visible to the package manager.") points to a package server.

Shouldn't it point to somewhere like [this](http://pkgdocs.julialang.org/v1/creating-packages/#Registering-packages) or [this](https://julialang.org/packages/)?

**Comment by hsugawa8651** [comment]
Or [this](https://github.com/JuliaRegistries/General#registering-a-package-in-general)
