### ISSUE TITLE
workflow's link is failed

### ISSUE THREAD

**Issue by dlintw** [JuliaDocs/Julia-Cheat-Sheet#17]
Julia has an LLVM-based JIT compiler that allows it to match the performance of languages such as C and FORTRAN without the hassle of low-level code. Because the code is compiled on the fly you can run (bits of) code in a shell or REPL, which is part of the recommended workflow.

This link in 'workflow' is wrong now.

**Comment by mortenpi** [comment]
Fixed in #18.
