### ISSUE TITLE
Typo in performance tips?

### ISSUE THREAD

**Issue by orialb** [JuliaDocs/Julia-Cheat-Sheet#23]
Hi, thanks for the great cheat sheet!

One of the performance tips is ”devectorizing does not improve performance “
I guess it should be “vectorizing does not improve performance “?

**Comment by nickeubank** [comment]
Sounds great – thanks so much!

**Comment by orialb** [comment]
submitted PR #24 .
If we are already at fixing typos - the description of the repository "Julia v0.6 Cheat Sheet" 
should probably be changed to "Julia v1.0 Cheat Sheet" as the link refers to the 1.0 sheet.

**Comment by nickeubank** [comment]
Yeah, issue #22  is already open for the v1.0 title. That requires @brakmic to fix, since not actually *in* the repo. 

Thanks for the help on this!

**Comment by orialb** [comment]
Ah sorry, didn't notice this somehow, seems it was already updated .
