### ISSUE TITLE
feature request: Standard Library function listing

### ISSUE THREAD

**Issue by wherrera10** [JuliaDocs/Julia-Cheat-Sheet#30]
Please add a section with each of the functions in the Standard Library listed under or with the library to use to get such.

So, **I** would be listed under the LinearAlgeba library, and so forth.

**Comment by nickeubank** [comment]
Nice idea... A full list of functions in each library would be overwhelming, but maybe just a list of really commonly used standard libraries would be nice. Random, Statistics, LinearAlgebra, Pkg, Test...

**Comment by nickeubank** [comment]
@wherrera10 added PR. That look like what you had in mind?

![screen shot 2018-09-29 at 6 37 01 pm](https://user-images.githubusercontent.com/9683693/46251379-af0d2900-c416-11e8-8a76-a41a8e531734.png)

**Comment by wherrera10** [comment]
yes. Nice!
