### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaDocs/Julia-Cheat-Sheet#39]
I'm preparing a workshop on open source and collaboration for [Hacktoberfest](https://hacktoberfest.digitalocean.com/) and translating this cheat sheet would be a very fine exercise for a group of people.
To that end, I'm making a few modifications on a [separate package](https://github.com/abelsiqueira/Julia-Cheat-Sheet-pt-br/tree/gh-pages):

- Use `jekyll`;
- Break `index.html` to several files (one for each box); and
- Convert each box from HTML to Markdown whenever possible.

Is this process of interest to the package? I can open a PR with the modifications above.

**Comment by nickeubank** [comment]
Sounds terrific to me!

**Comment by nickeubank** [comment]
@abelsiqueira Followup: one recent suggestion was that we add some tests to make sure everything in cheatsheet works. Is that something that could be done with `jekyll`? Never used before...

**Comment by abelsiqueira** [comment]
AFAIK no, `jekyll` will just build the site. Maybe creating a test script and a `.travis.yml` would work better and would be easier to maintain.

**Comment by nickeubank** [comment]
yeah, that's probably what we'll do then. Thanks!

**Comment by nickeubank** [comment]
(Though I don't have merge authority here -- @brakmic , thoughts?)

**Comment by brakmic** [comment]
I could simply transfer the rights to anyone who's willing to take care of this repo. No problem with that 😄

**Comment by brakmic** [comment]
So, I've sent you an invite, @nickeubank

**Comment by sheilagomes** [comment]
Duas dúvidas:
1) Como posso ajudar a traduzir? Sou tradutora por profissão e uso ferramentas próprias pra isso, mas não quero atrapalhar o processo se alguém já estiver fazendo.
2) Por que a comunicação está em inglês (só de curiosa mesmo :) )?

**Comment by abelsiqueira** [comment]
Olá,

1. Estou organizando ainda a tradução, devo criar uma issue pra isso. Eu estou preparando para o [Hacktoberfest](hacktoberfest.digitalocean.com), pois vamos fazer um [encontro local em Curitiba](https://github.com/hacktoberfestcwb/2018), inclusive te convido a apresentar algo, se tiver disponibilidade.
2. Porque essa issue era da estrutura dos arquivos para traduções em geral, não só para pt-br. Inclusive acredito que o pessoal acima não fala português.

**Comment by sheilagomes** [comment]
Obrigada, @abelsiqueira ! Quero participar do encontro, já me inscrevi na Hacktoberfest. Não sei se tenho algo a contribuir, até conheço HTML, CSS, Javascrit e Python, mas tudo iniciante, e faço parte da comunidade do WordPress aqui de Curitiba. Se interessar, sou tradutora e localizadora, então posso falar sobre localização de software com auxílio de software livre, por exemplo. Ou sobre o FreeCode Camp também, que estou fazendo. Ou sobre trabalho freelancer, pois sou profissional autônoma que trabalha com agências no exterior.. Enfim, se achar que vale, é só dizer. 
Quanto às traduções, consigo traduzir direto de código, se for o caso, internacionalizado ou não. Vou aguardar teu retorno. Valeu e até mais!

**Comment by abelsiqueira** [comment]
Mandei uma mensagem no repositório do hacktoberfest pra fechar esta issue. Quando começar a organizar a tradução te marco.

**Comment by nickeubank** [comment]
I'm afraid my Portuguese is... non-existent, but grabbing a few spanish cognates, sounds like you're thinking of writing a translated version of the cheatsheet? If so, that sounds AWESOME, and would be happy to merge any PRs that accomplish that goal.

**Comment by nickeubank** [comment]
With my wife's help:

Ou nao falo portuguese (mais gracias a deus a minha esposa fala), mais ou estou feliz por mesclar/fundir (?) qualquer PRs que cria versoes traducidas.

**Comment by abelsiqueira** [comment]
Haha, good to see Portuguese so widespread!

We intend to create an issue and separate the work for future PRs soon, thanks.
