### ISSUE TITLE
fyi...

### ISSUE THREAD

**Issue by nickeubank** [JuliaDocs/Julia-Cheat-Sheet#5]
you may get a little more traffic in coming days, as I put your [beautiful cheatsheet on the julia community pages](https://discourse.julialang.org/t/excellent-cheat-sheet/7792).

**Comment by brakmic** [comment]
Oh, ...many, many thanks 💯 😄

**Comment by nickeubank** [comment]
@brakmic You may have seen this already, but there's an [invitation to roll your cheat-sheet into the official Julia docs](https://discourse.julialang.org/t/excellent-cheat-sheet/7792/5) if you're interested!

**Comment by brakmic** [comment]
Yeah, no problem. I too think I'd be much better to put the cheat sheet there.
As I'm not in touch with the people there I'd be nice if someone could "ping" them with the idea 😄

**Comment by nickeubank** [comment]
@brakmic Will see what I can do!

**Comment by mortenpi** [comment]
If you think that JuliaDocs would be a better home for this then we could definitely have it under there. Feel free to initiate the transfer, I can accept it. @brakmic, I'll add you as an admin and you can take it from there again.

**Comment by brakmic** [comment]
Hi @mortenpi,
I've tried to initiate the transfer, but needed rights are missing. 😄

**Comment by mortenpi** [comment]
GitHub is a bit weird here. Can you transfer it to me and I'll transfer it to the org?

**Comment by brakmic** [comment]
Ok, I'll do it 😄

**Comment by mortenpi** [comment]
Done :smile:

**Comment by brakmic** [comment]
Thanks 👍

**Comment by mortenpi** [comment]
The URL needs to be updated now I guess. The new site is already live: https://juliadocs.github.io/Julia-Cheat-Sheet/

**Comment by brakmic** [comment]
Done 👍
