### ISSUE TITLE
a typo in the Arrays section

### ISSUE THREAD

**Issue by BoundaryValueProblems** [JuliaDocs/Julia-Cheat-Sheet#71]
There's a small typo in the ```Arrays``` section:
```Select subarray from m to n | arr[n:m]```
This should be of course:
```Select subarray from m to n | arr[m:n]```
Thanks for fixing this. Or should I do pull request?

**Comment by brakmic** [comment]
PR is preferred. Thanks!

**Comment by abelsiqueira** [comment]
Closed by #72
